version: '3'

services:
  app:
    build: .
    image: junweizhou/task-notification:1.0.0
    container_name: task-notification
    restart: unless-stopped
    ports:
      - "8002:8002"
    volumes:
      - task-notification-data:/usr/src/app/data
    environment:
      - NODE_ENV=production

volumes:
  task-notification-data: 