version: '3'

services:
  app:
    build: .
    image: junweizhou/task-notification:1.0.4
    container_name: task-notification
    restart: unless-stopped
    ports:
      - "8002:8002"
    volumes:
      - task-notification-data:/usr/src/app/data
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai
      - NODE_OPTIONS=--max-old-space-size=512
    # 添加资源限制
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M

volumes:
  task-notification-data: 
